services:
  openmemory-mcp:
    image: mem0/openmemory-mcp:latest
    build: api/
    environment:
      - USER=zhangjianyong
      - OPENAI_API_KEY=sk-4695b3a1c3fe4d2b90830e71928d0ece
      - EMBEDDER_PROVIDER=openai
      - EMBEDDER_MODEL=text-embedding-v4
      - EMBEDDER_API_KEY=sk-4695b3a1c3fe4d2b90830e71928d0ece
      - EMBEDDER_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode/v1
      - LLM_PROVIDER=openai
      - LLM_MODEL=qwen-max
      - LLM_API_KEY=sk-4695b3a1c3fe4d2b90830e71928d0ece
      - LLM_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode/v1
      - QDRANT_HOST=host.docker.internal
      - QDRANT_PORT=6333
    ports:
      - "8765:8765"
    volumes:
      - ./api:/usr/src/openmemory
      - openmemory_db:/usr/src/openmemory/data
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8765 --reload --workers 2"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  openmemory_db:
